<?php if ($this->enabled) :

/* @var $visits \Grid\GoogleAnalytics\Model\AbstractGoogleAnalyticsApi\Result\Visits */
$visits = $this->visits;

$script = '
    google.load("visualization", "1", {packages:["corechart"], "language": "' . $this->locale() . '"});
    google.setOnLoadCallback(googleAnalyticsDiagramDrawChart);
    
    function googleAnalyticsDiagramDrawChart() {
        var data = google.visualization.arrayToDataTable([
                ["Month",   "' . $this->translate( 'googleAnalytics.admin.diagram.data.label' ) . '"   ],
';

foreach ($visits->getData()['visits'] as $date => $count) {
    $datePieces = explode('-', $date);
    $script .= '                [new Date(' . $datePieces[0] . ', ' . ($datePieces[1] - 1 ) . ', ' . $datePieces[2] . '), ' . $count . ' ],' . PHP_EOL;
    
}
 $script .= '
        ]); 
        
        var target = new google.visualization.AreaChart(document.getElementById("googleAnalyticsDiagram"));
        
        target.draw(data, {
            isStacked: true,
            lineWidth: 3,
            pointSize: 5,
            legend: {position: "top"},
            hAxis: {  ticks: [new Date(2014, 01, 12), new Date(2014, 01, 15), new Date(2014, 01, 18)], gridlines : {color: "#FFF"} }
        });
    }
';


$this->headLink()->appendStylesheet( '/styles/modules/GoogleAnalytics/admin.dashboard.box.css' );
$this->headScript()->appendFile( 'https://www.google.com/jsapi' );
$this->headscript()->appendScript($script);

?>
<section class="innerPanel">
    <section id="innerPanelGoogleAnalytics">
        <h1><?= $this->translate( 'googleAnalytics.admin.diagram.box.title' ) ?></h1>
        <div class="innerPanelContent">
            <div class="title"><?php echo $this->visits->getTitle() ?></div>
            <div id="googleAnalyticsDiagram"></div>
            <div class="link"><a href="<?php echo $this->visits->getReportLink() ?>" target="_blank"><?php echo $this->translate('googleAnalytics.admin.diagram.box.linkToReport') ?></a></div>
        </div>
    </section>
</section>
<?php endif; ?>
