<?php 

/* @var $visits \Grid\GoogleAnalytics\Model\AbstractGoogleAnalyticsApi\Result\Visits */
$visits = $this->visits;

?>
<script type="text/javascript">

var parentWindow = null;

if (window.opener) {
	parentWindow = window.opener; 
} else if (parent) {
	parentWindow = parent;
}

var dataTable = [
    ["Day",   "<?php echo $this->translate( 'googleAnalytics.admin.diagram.data.label' ) ?>"   ],
    <?php foreach ($visits->getData()['visits'] as $date => $count) : ?>
        <?php $datePieces = explode('-', $date); ?>
        [new Date(<?php echo $datePieces[0] ?>,<?php echo ($datePieces[1] - 1 )?>,<?php echo $datePieces[2]?>),<?php echo $count?>],
    <?php endforeach; ?>
];


parentWindow.googleAnalyticsDiagramDrawChart(dataTable);

var link = parentWindow.document.getElementById("innerPanelGoogleAnalytics_link");
link.href = "<?php echo $visits->getReportLink() ?>";

var titleDiv = parentWindow.document.getElementById("innerPanelGoogleAnalytics_title");
titleDiv.innerHTML = "<?php echo $visits->getTitle() ?>";

if (window.opener) {
	window.close(); 
} else if (parent) {
	var element = parent.document.getElementById("innerPanelGoogleAnalytics_iframe");
	element.parentNode.removeChild(element);
}


</script>
